### ISSUE TITLE
conda workflow 

### ISSUE THREAD

**Issue by matt-long** [ncar-hackathons/administration#3]
@khallock has volunteered put together some material on using `conda`. 

We can use material we've compiled previously
https://github.com/NCAR/NCAR-pangeo-tutorial

@andersy005, please help Kevin to get going with a repo.

**Comment by andersy005** [comment]
@matt-long, should we create a new repo for this or use the existing python-general existing repo and add a new conda section to it? Either option is okay

**Comment by matt-long** [comment]
seems like a distinct topic and we want a bash kernel, so probably a new repo.

**Comment by andersy005** [comment]
Sounds good. what do you think of a repo named `package-management`? This repo could presumably cover other topics such as pip, packaging for pypi and conda channels and so on?

**Comment by matt-long** [comment]
that could work, but I think is important that we clear distinguish and target content towards two distinct perspectives: 
- all users need to learn skills for proactive package management, including pip and conda;
- people interested in becoming developers will want to learn about packaging.

**Comment by andersy005** [comment]
@matt-long, @khallock 

The [repo](https://github.com/ncar-hackathons/package-management) is ready.  I am going to add some documentation on how to add content to it later. 

In summary, following these steps should be enough:

- fork and clone the repo
- Add content to https://github.com/ncar-hackathons/package-management/tree/master/content/conda directory. Content can be in form of a markdown file or jupyter notebook 
- In case a new markdown or notebook file is created, add it to `toc.yml` file in https://github.com/ncar-hackathons/package-management/blob/master/_data/toc.yml

- Commit & push and open PR against the upstream repo 
- Once the PR is merged, the website is built and updated. The content of the website is accessible at https://ncar-hackathons.github.io/package-management

**Comment by matt-long** [comment]
Awesome! Thanks!

**Comment by khallock** [comment]
Thanks @matt-long and @andersy005 for getting this set up! I'll take a look at it soon.

**Comment by matt-long** [comment]
Looks like we're on track here, so I'll close this issue.
